In [1]:
import pandas as pd

In [2]:
#data structures: series and DataFrame

In [17]:
#DataFrame
info = {
    "Name": ["A","B","C"],
    "CGPA": [9,8.5,8.8]
}
df = pd.DataFrame(info)
print(df)

#series
points = pd.Series([6,2,3,4,5])
print(points, type(points))

#index
print(points[0])

  Name  CGPA
0    A   9.0
1    B   8.5
2    C   8.8
0    6
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
6

In [6]:
df

  Name  CGPA
0    A   9.0
1    B   8.5
2    C   8.8

In [19]:
age = pd.Series([21,23,24,22],index=["A","B","C","D"])
print(age)

A    21
B    23
C    24
D    22
dtype: int64

In [23]:
#DataFrame
#1)
info = {
    "Name": ["A","B","C"],
    "CGPA": [9,8.5,8.8]
}
df = pd.DataFrame(info)
print(df)

#3)
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr, columns = (["A","B","C"]))
print(df)

  Name  CGPA
0    A   9.0
1    B   8.5
2    C   8.8
   A  B  C
0  1  2  3
1  4  5  6

In [25]:
#csv_data
df = pd.read_csv("emplyee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [26]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [37]:
#method
print(df.head()) #df.head()
df.tail()
df.sample()
df.info()
df.shape
df.describe()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [9]:
import pandas as pd

In [11]:
#Aqi data
df = pd.read_csv("globalairquality_data.csv")
df

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01

In [26]:
#data selection

#select cloumn
df["City"]
df[["City","Humidity"]]

#select row
df.loc[0]
df.loc[0:2] #[start idx : end idx(inclusive]

df.iloc[0]
df.iloc[0:2] #end idx(exclusive)

#select cell-row & column   df.loc[row, column]
df.loc[2,"Humidity"]
df.loc[0:2, ["City","Humidity"]]
df.iloc[0:2, 0:10] #In iloc pass the column index

#select single scaler value
df.at[0,"City"]
df.iat[0,0]

'Bangkok'